version: 2.1

shared: &shared
    docker:
    - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run: echo terraform init
      - run: echo terraform plan ${tfvarsfile}
      - run: if [[ "${tfvarsfile}" == "mysecondfile" ]]; then exit 1 ; fi
      - run: echo terraform destroy ${tfvarsfile}

jobs:
  ceubuntu:
    <<: *shared
    environment:
      - tfvarsfile: myfirstfile

  cerhel:
    <<: *shared
    environment:
      - tfvarsfile: mysecondfile


  eeubuntu:
    <<: *shared
    environment:
      - tfvarsfile: mythirdfile


workflows:
  version: 2
  build:
    jobs:
      - ceubuntu
      - cerhel:
          requires:
            - ceubuntu
      - eeubuntu:
          requires:
            - cerhel
