version: 2.0

shared: &shared
    docker:
    - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run: echo terraform init
      - run: echo terraform plan ${tfvarsfile}
      - run: if [[ "${tfvarsfile}" == "mysecondfile" ]]; then exit 1 ; fi
      - run: echo terraform destroy ${tfvarsfile}

jobs:
  "ruby-2.2":
    <<: *shared
    environment:
      - tfvarsfile: myfirstfile

  "ruby-2.3":
    <<: *shared
    environment:
      - tfvarsfile: mysecondfile


  "ruby-2.4":
    <<: *shared
    environment:
      - tfvarsfile: mythirdfile


workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.2"
      - "ruby-2.3"
      - "ruby-2.4"
