version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.14
    parameters:
      tfvarsfile:
        type: string
        default: notspecified
    steps:
      - checkout
      - run:
          name: Make backend for << parameters.tfvarsfile >>
          command: |
            cat \<<EOF > backend_override.tf
              terraform {
                  backend "s3" {
                    bucket = "${tfstatebucket}"
                    key    = "circledeployments/${CIRCLE_BUILD_NUM}-<< parameters.tfvarsfile >>.tfstate"
                    region = "${tfstateregion}"
                  }
                }
            EOF
      - run: terraform init
      - run:
        name: terraform plan
        command: terraform plan -var-file=<< parameters.tfvarsfile >> -out=mybuild
      - run:
        name: terraform apply
        command: terraform apply "mybuil"
      - run:
        name: terraform destroy
        command: terraform destroy -force
        when: always
workflows:
  workflow:
    jobs:
      - build:
          tfvarsfile: terraform-icp-ce-example.tfvars
      - build:
          requires:
            - build
          tfvarsfile: terraform-icp-ce-example.tfvars
