version: 2.0

shared: &shared
    docker:
    - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run: echo terraform init
      - run: echo terraform plan ${tfvarsfile}
      - run: if [[ "${tfvarsfile}" == "mysecondfile" ]]; then exit 1 ; fi
      - run: echo terraform destroy ${tfvarsfile}

jobs:
  ce-ubuntu:
    <<: *shared
    environment:
      - tfvarsfile: myfirstfile

  ce-rhel:
    <<: *shared
    environment:
      - tfvarsfile: mysecondfile


  ee-ubuntu:
    <<: *shared
    environment:
      - tfvarsfile: mythirdfile


workflows:
  version: 2
  build:
    jobs:
      - ce-ubuntu
      - ce-rhel
        requires:
          - ce-ubuntu
      - ee-ubuntu
        requires:
          - ce-rhel
