version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.14
    parameters:
      tfvarsfile:
        type: string
        default: notspecified
    steps:
      - run: echo "preinstall is << parameters.tfvarsfile >>"
      - checkout
      - run:
          name: Make backend
          command: |
            cat \<<EOF > backend_override.tf
              terraform {
                  backend "s3" {
                    bucket = "${tfstatebucket}"
                    key    = "circledeployments/${CIRCLE_BUILD_NUM}"
                    region = "${tfstateregion}"
                  }
                }
            EOF
      - run: echo terraform init
      - run: echo "preinstall is << parameters.tfvarsfile >>"
      - run: cat backend_override.tf
workflows:
  workflow:
    jobs:
      - build:
          tfvarsfile: some.tfvars
      - build:
          tfvarsfile: other.tfvars
