version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Make backend
          command: |
            cat <<EOF > backend_override.tf
              terraform {
                  backend "s3" {
                    bucket = "${tfstatebucket}"
                    key    = "circledeployments/${CIRCLE_BUILD_NUM}"
                    region = "${tfstateregion}"
                  }
                }
            EOF
      - run:
          name: Terraform init
          command: export MYVAR="my thing"
      - run:
          name: Plan ICP CE Ubuntu
          command: echo "This is $MYVAR"
      - run:
          name: Deploy and destroy ICP CE Ubuntu
          command: echo done
      - run:
          name: Plan ICP CE RHEL
          command: lets fail
      - run:
          name: Deploy and destroy ICP CE RHEL
          command: echo done
